### ISSUE TITLE
Verification for student IDs in Attendance

### ISSUE THREAD

**Issue by adriangotca98** [adriangotca98/eSIMS2.0#12]
You should verify that all IDs in that array exist in the database also. You can check my code on Students, I had to check the IDs for grades and subjects.

**Comment by lazarnmihai** [comment]
IDs looks good

**Comment by adriangotca98** [comment]
Nope, they don't, cause right now I can add Students that are not present in the database. For example, if I try to add student with ID 1, but the ID isn't present in the students collection, it should get me a bad request, or something other that OK 200.
